# Generated by Django 5.0.6 on 2024-09-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='文件保存路径')),
                ('temp_login', models.BooleanField(default=False, verbose_name='临时登录')),
                ('temp_pwd', models.CharField(default='123456', max_length=32, verbose_name='临时密码')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('img', '图片'), ('media', '音视频'), ('txt', '文档'), ('other', '其他')], default='other', max_length=10, verbose_name='文件类型')),
                ('introduce', models.TextField(default='', verbose_name='文件介绍')),
                ('file_name', models.CharField(default='', max_length=255, verbose_name='文件名')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_suffix', models.CharField(default='', max_length=20, verbose_name='文件后缀')),
                ('file_path', models.CharField(default='', max_length=255, verbose_name='文件文件夹路径')),
                ('full_file_path', models.CharField(default='', max_length=255, verbose_name='文件完整路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(KB)')),
                ('file_hash', models.CharField(default='sha256', max_length=255, verbose_name='文件hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_main.user', verbose_name='上传用户')),
            ],
        ),
    ]
